### ISSUE TITLE
Allow specification of `ttl` for cached commands

### ISSUE THREAD

**Issue by jmversteeg** [jmversteeg/katapult#39]
Parse human-readable times using Example:
```yaml
  - cmd: npm install
    input: package.json
    output: node_modules
    ttl: 1 day
```
Using [human-interval](https://www.npmjs.com/package/human-interval)
